spring:
  redis:
    #redis数据库，默认是0
    database: 1
    #redis服务器地址
    host: 159.75.136.164
    #redis服务端口，默认6379
    port: 6379
    #redis密码，默认为空
    password:

  thymeleaf:
    mode: LEGACYHTML5
    cache: false
server:
  port: 8989
